language: node_js

node_js:
  - "0.10"
  - "4.4"

env:
  - CXX=g++-4.8
  - CXX=g++-4.8 KAFKA_URL=kafka://127.0.0.1:9093 KAFKA_CLIENT_CERT=${TRAVIS_BUILD_DIR}/test/ssl/client.crt KAFKA_CLIENT_CERT_KEY=${TRAVIS_BUILD_DIR}/test/ssl/client.key
  # - CXX=g++-4.8 KAFKA_URL=kafka://127.0.0.1:9093 KAFKA_CLIENT_CERT_STR="`cat ${TRAVIS_BUILD_DIR}/test/ssl/client.crt`" KAFKA_CLIENT_CERT_KEY_STR="`cat ${TRAVIS_BUILD_DIR}/test/ssl/client.key`"

addons:
  code_climate:
    repo_token: 3ea8622d957330fec45b641e8ed2650f7a83bc905a38d94f3d43738caf8b227a
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - wget http://www.us.apache.org/dist/kafka/0.10.0.0/kafka_2.11-0.10.0.0.tgz -O kafka.tgz
  - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
  # - sed -i -e 's|listeners=PLAINTEXT://:9092|listeners=PLAINTEXT://:9092,SSL://:9093|' kafka/config/server.properties
  - echo "listeners=PLAINTEXT://:9092,SSL://:9093" >> kafka/config/server.properties
  - echo "ssl.keystore.location=${TRAVIS_BUILD_DIR}/test/ssl/server.keystore.jks" >> kafka/config/server.properties
  - echo "ssl.keystore.password=test1234" >> kafka/config/server.properties
  - echo "ssl.key.password=test1234" >> kafka/config/server.properties;
  - echo "ssl.truststore.location=${TRAVIS_BUILD_DIR}/test/ssl/server.truststore.jks" >> kafka/config/server.properties
  - echo "ssl.truststore.password=test1234" >> kafka/config/server.properties
  - nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
  - sleep 10
  - nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"
  - sleep 10
  - kafka/bin/kafka-topics.sh --zookeeper 127.0.0.1:2181 --create --topic kafka-test-topic --partitions 3 --replication-factor 1

after_script:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
