language: node_js
sudo: required

node_js:
  - "8.12"
  - "4.4"

env:
  - CXX=g++-4.8
  - CXX=g++-4.8 KAFKA_URL=kafka://127.0.0.1:9093 KAFKA_CLIENT_CERT="${TRAVIS_BUILD_DIR}/test/ssl/client.crt" KAFKA_CLIENT_CERT_KEY="${TRAVIS_BUILD_DIR}/test/ssl/client.key"
  # - CXX=g++-4.8 KAFKA_URL=kafka://127.0.0.1:9093 KAFKA_CLIENT_CERT_STR="`cat ${TRAVIS_BUILD_DIR}/test/ssl/client.crt`" KAFKA_CLIENT_CERT_KEY_STR="`cat ${TRAVIS_BUILD_DIR}/test/ssl/client.key`"

addons:
  code_climate:
    repo_token:
      secure: "rcV5wogvH+miosc5xPb5YGNAfIrcoHi59TfDvGep4aBCxNqaU/YsFBVrnwyU24GeX8l1Fstoo2voYv3bOrSKcAHSLOXdBGIAg9tw2dVFD0wHXF8HctD2yWQdWPsUNdrv7UUm9n54RmYPMpKKH/jEYbU9l3JeP4jPZCdiPy4jy9SZRn4g338m3KPzGPOPxZza71d9WQHaio5wkuveBzU5DOJtqS4KcaTEsMZGHyWB448j4sSmktUpc5roeRbHRFIt1duGWj3C52ujAYWrVfCOzxvAKIrExHqj2bpxpv8lQHdOgfnbOx+QAzkMqc33wsbPRE/vFDkMXBTXR7aB5Nz5P1OkRI6Gg8yOEIM2DaD4XP3SgNQpXf1rgu3xkuVXJ62/W0ef8CLca+Fmiml9b3ZQ5PleNzsGtYMZc0ii7eqjJiH7sxJk2uZU14qqEROO2ge/o6c+EOQwfPE6iF+COi3bBYza7tZBldzld1d89N6mYi5/CkkwwRS1bddCpkepnhevlNqvCrZNckcIM5xDCd8gofyh0Pre3dJ8lEFCA68SxOIJODcH5impRhY/Tp2eav1b54eQFaSQOn1Kc34YPhmZu6GKXIjxZ/w1J1WOmWpqQYzpeAGLdZmFrd/iDzgzAdzxGDlF+kxhOe41Yd6MnAXeaHOJtEIWn+UadKVr8ddS4sI="
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
    update: true

services:
  - docker

before_install:
  - docker pull spotify/kafka

after_script:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
